package com.example.WebBanHang.Controller;

import java.util.Arrays;
import java.util.List;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.example.WebBanHang.model.District;
import com.example.WebBanHang.model.Province;

@RestController
@RequestMapping("/provinces")
public class ProvinceController {

    @GetMapping("/all")
    public List<Province> getAllProvinces() {
        return Arrays.asList(
                new Province(1, "Hà Nội", Arrays.asList(
                        new District(1, "Ba Đình"),
                        new District(2, "Hoàn Kiếm"),
                        new District(3, "Tây Hồ"),
                        new District(4, "Cầu Giấy"),
                        new District(5, "Đống Đa"),
                        new District(6, "Thanh Xuân"),
                        new District(7, "Hà Đông"),
                        new District(8, "Long Biên"),
                        new District(9, "Nam Từ Liêm"),
                        new District(10, "Bắc Từ Liêm"),
                        new District(11, "Hoàng Mai"),
                        new District(12, "Thanh Trì"))),
                new Province(26, "Đà Nẵng", Arrays.asList(
                        new District(13, "Hải Châu"),
                        new District(14, "Thanh Khê"),
                        new District(15, "Sơn Trà"),
                        new District(16, "Ngũ Hành Sơn"),
                        new District(17, "Liên Chiểu"),
                        new District(18, "Cẩm Lệ"),
                        new District(19, "Hòa Vang"),
                        new District(20, "Hoàng Sa"))),
                new Province(27, "Quảng Nam", Arrays.asList(
                        new District(21, "Tam Kỳ"),
                        new District(22, "Hội An"),
                        new District(23, "Điện Bàn"),
                        new District(24, "Đại Lộc"),
                        new District(25, "Duy Xuyên"),
                        new District(26, "Quế Sơn"),
                        new District(27, "Thăng Bình"),
                        new District(28, "Núi Thành"),
                        new District(29, "Phú Ninh"),
                        new District(30, "Tiên Phước"))),
                new Province(44, "Hồ Chí Minh", Arrays.asList(
                        new District(31, "Quận 1"),
                        new District(32, "Quận 2"),
                        new District(33, "Quận 3"),
                        new District(34, "Quận 4"),
                        new District(35, "Quận 5"),
                        new District(36, "Quận 6"),
                        new District(37, "Quận 7"),
                        new District(38, "Quận 8"),
                        new District(39, "Quận 9"),
                        new District(40, "Quận 10"),
                        new District(41, "Quận 11"),
                        new District(42, "Quận 12"),
                        new District(43, "Tân Bình"),
                        new District(44, "Bình Thạnh"),
                        new District(45, "Thủ Đức"),
                        new District(46, "Gò Vấp"),
                        new District(47, "Phú Nhuận"),
                        new District(48, "Bình Tân"),
                        new District(49, "Củ Chi"),
                        new District(50, "Hóc Môn"),
                        new District(51, "Bình Chánh"),
                        new District(52, "Nhà Bè"),
                        new District(53, "Cần Giờ"))),
                new Province(2, "Hà Giang", Arrays.asList(
                        new District(54, "Thành phố Hà Giang"),
                        new District(55, "Đồng Văn"),
                        new District(56, "Mèo Vạc"),
                        new District(57, "Yên Minh"),
                        new District(58, "Quản Bạ"),
                        new District(59, "Vị Xuyên"),
                        new District(60, "Bắc Mê"),
                        new District(61, "Hoàng Su Phì"),
                        new District(62, "Xín Mần"))),
                new Province(3, "Cao Bằng", Arrays.asList(
                        new District(63, "Thành phố Cao Bằng"),
                        new District(64, "Bảo Lạc"),
                        new District(65, "Bảo Lâm"),
                        new District(66, "Hà Quảng"),
                        new District(67, "Hòa An"),
                        new District(68, "Nguyên Bình"),
                        new District(69, "Quảng Hòa"),
                        new District(70, "Thạch An"),
                        new District(71, "Trùng Khánh"))),
                new Province(4, "Nghệ An", Arrays.asList(
                        new District(72, "Thành phố Vinh"),
                        new District(73, "Thị xã Cửa Lò"),
                        new District(74, "Thị xã Thái Hòa"),
                        new District(75, "Huyện Anh Sơn"),
                        new District(76, "Huyện Con Cuông"),
                        new District(77, "Huyện Diễn Châu"),
                        new District(78, "Huyện Đô Lương"),
                        new District(79, "Huyện Hưng Nguyên"),
                        new District(80, "Huyện Nam Đàn"),
                        new District(81, "Huyện Nghĩa Đàn"),
                        new District(82, "Huyện Nghi Lộc"),
                        new District(83, "Huyện Quỳ Châu"),
                        new District(84, "Huyện Quỳ Hợp"),
                        new District(85, "Huyện Quỳnh Lưu"),
                        new District(86, "Huyện Tân Kỳ"),
                        new District(87, "Huyện Thanh Chương"),
                        new District(88, "Huyện Tương Dương"),
                        new District(89, "Huyện Yên Thành"))),

                new Province(5, "Đắk Lắk", Arrays.asList(
                        new District(90, "Thành phố Buôn Ma Thuột"),
                        new District(91, "Thị xã Buôn Hồ"),
                        new District(92, "Huyện Buôn Đôn"),
                        new District(93, "Huyện Cư Kuin"),
                        new District(94, "Huyện Cư M'gar"),
                        new District(95, "Huyện Ea H'leo"),
                        new District(96, "Huyện Ea Kar"),
                        new District(97, "Huyện Ea Súp"),
                        new District(98, "Huyện Krông Ana"),
                        new District(99, "Huyện Krông Bông"),
                        new District(100, "Huyện Krông Buk"),
                        new District(101, "Huyện Krông Năng"),
                        new District(102, "Huyện Krông Pắc"),
                        new District(103, "Huyện Lắk"),
                        new District(104, "Huyện M'Đrắk"))),

                new Province(6, "Đồng Nai", Arrays.asList(
                        new District(105, "Thành phố Biên Hòa"),
                        new District(106, "Thành phố Long Khánh"),
                        new District(107, "Huyện Cẩm Mỹ"),
                        new District(108, "Huyện Định Quán"),
                        new District(109, "Huyện Long Thành"),
                        new District(110, "Huyện Nhơn Trạch"),
                        new District(111, "Huyện Tân Phú"),
                        new District(112, "Huyện Thống Nhất"),
                        new District(113, "Huyện Trảng Bom"),
                        new District(114, "Huyện Vĩnh Cửu"),
                        new District(115, "Huyện Xuân Lộc"))),
                new Province(4, "An Giang", Arrays.asList(
                        new District(72, "Thành phố Long Xuyên"),
                        new District(73, "Thành phố Châu Đốc"),
                        new District(74, "Thị xã Tân Châu"),
                        new District(75, "Huyện An Phú"),
                        new District(76, "Huyện Châu Phú"),
                        new District(77, "Huyện Châu Thành"),
                        new District(78, "Huyện Chợ Mới"),
                        new District(79, "Huyện Phú Tân"),
                        new District(80, "Huyện Thoại Sơn"),
                        new District(81, "Huyện Tịnh Biên"),
                        new District(82, "Huyện Tri Tôn"))),

                new Province(5, "Bình Dương", Arrays.asList(
                        new District(83, "Thành phố Thủ Dầu Một"),
                        new District(84, "Thành phố Dĩ An"),
                        new District(85, "Thành phố Thuận An"),
                        new District(86, "Thị xã Bến Cát"),
                        new District(87, "Thị xã Tân Uyên"),
                        new District(88, "Huyện Bắc Tân Uyên"),
                        new District(89, "Huyện Bàu Bàng"),
                        new District(90, "Huyện Dầu Tiếng"),
                        new District(91, "Huyện Phú Giáo"))),

                new Province(6, "Thái Nguyên", Arrays.asList(
                        new District(92, "Thành phố Thái Nguyên"),
                        new District(93, "Thành phố Sông Công"),
                        new District(94, "Thị xã Phổ Yên"),
                        new District(95, "Huyện Đại Từ"),
                        new District(96, "Huyện Định Hóa"),
                        new District(97, "Huyện Đồng Hỷ"),
                        new District(98, "Huyện Phú Bình"),
                        new District(99, "Huyện Phú Lương"),
                        new District(100, "Huyện Võ Nhai"))),
                new Province(7, "Quảng Ninh", Arrays.asList(
                        new District(101, "Thành phố Hạ Long"),
                        new District(102, "Thành phố Cẩm Phả"),
                        new District(103, "Thành phố Móng Cái"),
                        new District(104, "Thành phố Uông Bí"),
                        new District(105, "Thị xã Đông Triều"),
                        new District(106, "Thị xã Quảng Yên"),
                        new District(107, "Huyện Ba Chẽ"),
                        new District(108, "Huyện Bình Liêu"),
                        new District(109, "Huyện Cô Tô"),
                        new District(110, "Huyện Đầm Hà"),
                        new District(111, "Huyện Hải Hà"),
                        new District(112, "Huyện Tiên Yên"),
                        new District(113, "Huyện Vân Đồn"))),

                new Province(8, "Vĩnh Phúc", Arrays.asList(
                        new District(114, "Thành phố Vĩnh Yên"),
                        new District(115, "Thành phố Phúc Yên"),
                        new District(116, "Huyện Bình Xuyên"),
                        new District(117, "Huyện Lập Thạch"),
                        new District(118, "Huyện Sông Lô"),
                        new District(119, "Huyện Tam Dương"),
                        new District(120, "Huyện Tam Đảo"),
                        new District(121, "Huyện Vĩnh Tường"),
                        new District(122, "Huyện Yên Lạc"))),

                new Province(9, "Hậu Giang", Arrays.asList(
                        new District(123, "Thành phố Vị Thanh"),
                        new District(124, "Thành phố Ngã Bảy"),
                        new District(125, "Thị xã Long Mỹ"),
                        new District(126, "Huyện Châu Thành"),
                        new District(127, "Huyện Châu Thành A"),
                        new District(128, "Huyện Long Mỹ"),
                        new District(129, "Huyện Phụng Hiệp"),
                        new District(130, "Huyện Vị Thủy"))),
                new Province(10, "Bình Thuận", Arrays.asList(
                        new District(131, "Thành phố Phan Thiết"),
                        new District(132, "Thị xã La Gi"),
                        new District(133, "Huyện Bắc Bình"),
                        new District(134, "Huyện Hàm Thuận Bắc"),
                        new District(135, "Huyện Hàm Thuận Nam"),
                        new District(136, "Huyện Tuy Phong"),
                        new District(137, "Huyện Đức Linh"),
                        new District(138, "Huyện Tánh Linh"),
                        new District(139, "Huyện Phú Quý"))),

                new Province(11, "Hà Nam", Arrays.asList(
                        new District(140, "Thành phố Phủ Lý"),
                        new District(141, "Huyện Bình Lục"),
                        new District(142, "Huyện Duy Tiên"),
                        new District(143, "Huyện Kim Bảng"),
                        new District(144, "Huyện Lý Nhân"),
                        new District(145, "Huyện Thanh Liêm"))),

                new Province(12, "Khánh Hòa", Arrays.asList(
                        new District(146, "Thành phố Nha Trang"),
                        new District(147, "Thành phố Cam Ranh"),
                        new District(148, "Thị xã Ninh Hòa"),
                        new District(149, "Huyện Diên Khánh"),
                        new District(150, "Huyện Khánh Vĩnh"),
                        new District(151, "Huyện Cam Lâm"),
                        new District(152, "Huyện Khánh Sơn"),
                        new District(153, "Huyện Trường Sa"))),
                new Province(13, "Đồng Tháp", Arrays.asList(
                        new District(154, "Thành phố Cao Lãnh"),
                        new District(155, "Thành phố Sa Đéc"),
                        new District(156, "Thị xã Hồng Ngự"),
                        new District(157, "Huyện Cao Lãnh"),
                        new District(158, "Huyện Châu Thành"),
                        new District(159, "Huyện Hồng Ngự"),
                        new District(160, "Huyện Lai Vung"),
                        new District(161, "Huyện Lấp Vò"),
                        new District(162, "Huyện Tam Nông"),
                        new District(163, "Huyện Tân Hồng"),
                        new District(164, "Huyện Thanh Bình"),
                        new District(165, "Huyện Tháp Mười"))),
                new Province(14, "Lâm Đồng", Arrays.asList(
                        new District(166, "Thành phố Đà Lạt"),
                        new District(167, "Thành phố Bảo Lộc"),
                        new District(168, "Huyện Đạ Huoai"),
                        new District(169, "Huyện Đạ Tẻh"),
                        new District(170, "Huyện Đam Rông"),
                        new District(171, "Huyện Lạc Dương"),
                        new District(172, "Huyện Lâm Hà"),
                        new District(173, "Huyện Cát Tiên"),
                        new District(174, "Huyện Đức Trọng"),
                        new District(175, "Huyện Ninh Sơn"),
                        new District(176, "Huyện Tân Phú"))),

                new Province(15, "Phú Yên", Arrays.asList(
                        new District(177, "Thành phố Tuy Hòa"),
                        new District(178, "Thị xã Sông Cầu"),
                        new District(179, "Huyện Đồng Xuân"),
                        new District(180, "Huyện Phú Hòa"),
                        new District(181, "Huyện Tây Hòa"),
                        new District(182, "Huyện Tuy An"),
                        new District(183, "Huyện Sơn Hòa"),
                        new District(184, "Huyện Sông Hinh"),
                        new District(185, "Huyện Đông Hòa"),
                        new District(186, "Huyện Phú Sơn"))),
                new Province(16, "Bình Định", Arrays.asList(
                        new District(187, "Thành phố Quy Nhơn"),
                        new District(188, "Thị xã An Nhơn"),
                        new District(189, "Huyện An Lão"),
                        new District(190, "Huyện Hoài Ân"),
                        new District(191, "Huyện Hoài Nhơn"),
                        new District(192, "Huyện Phù Cát"),
                        new District(193, "Huyện Phù Mỹ"),
                        new District(194, "Huyện Tuy Phước"),
                        new District(195, "Huyện Vân Canh"))),

                new Province(17, "Quảng Bình", Arrays.asList(
                        new District(196, "Thành phố Đồng Hới"),
                        new District(197, "Thị xã Ba Đồn"),
                        new District(198, "Huyện Bố Trạch"),
                        new District(199, "Huyện Quảng Ninh"),
                        new District(200, "Huyện Quảng Trạch"),
                        new District(201, "Huyện Lệ Thủy"),
                        new District(202, "Huyện Tuyên Hóa"),
                        new District(203, "Huyện Minh Hóa"),
                        new District(204, "Huyện Sơn Hóa"))),

                new Province(18, "Bà Rịa - Vũng Tàu", Arrays.asList(
                        new District(205, "Thành phố Vũng Tàu"),
                        new District(206, "Thành phố Bà Rịa"),
                        new District(207, "Thị xã Phú Mỹ"),
                        new District(208, "Huyện Châu Đức"),
                        new District(209, "Huyện Côn Đảo"),
                        new District(210, "Huyện Đất Đỏ"),
                        new District(211, "Huyện Long Điền"),
                        new District(212, "Huyện Tân Thành"))),
                new Province(19, "Kiên Giang", Arrays.asList(
                        new District(213, "Thành phố Rạch Giá"),
                        new District(214, "Thành phố Hà Tiên"),
                        new District(215, "Huyện An Biên"),
                        new District(216, "Huyện An Minh"),
                        new District(217, "Huyện Châu Thành"),
                        new District(218, "Huyện Giang Thành"),
                        new District(219, "Huyện Hòn Đất"),
                        new District(220, "Huyện Kiên Hải"),
                        new District(221, "Huyện Kiên Lương"),
                        new District(222, "Huyện Phú Quốc"),
                        new District(223, "Huyện Tân Hiệp"),
                        new District(224, "Huyện U Minh Thượng"),
                        new District(225, "Huyện Vĩnh Thuận"))),
                new Province(21, "Gia Lai", Arrays.asList(
                        new District(254, "Thành phố Pleiku"),
                        new District(255, "Thị xã An Khê"),
                        new District(256, "Huyện Ayun Pa"),
                        new District(257, "Huyện Chư Păh"),
                        new District(258, "Huyện Chư Prông"),
                        new District(259, "Huyện Chư Sê"),
                        new District(260, "Huyện Đăk Đoa"),
                        new District(261, "Huyện Đăk Pơ"),
                        new District(262, "Huyện Ia Grai"),
                        new District(263, "Huyện Ia Pa"),
                        new District(264, "Huyện Kbang"),
                        new District(265, "Huyện Krông Pa"),
                        new District(266, "Huyện Mang Yang"),
                        new District(267, "Huyện Phú Thiện"),
                        new District(268, "Huyện Tây Sơn"))),
                new Province(22, "Thừa Thiên - Huế", Arrays.asList(
                        new District(269, "Thành phố Huế"),
                        new District(270, "Thị xã Hương Thủy"),
                        new District(271, "Thị xã Hương Trà"),
                        new District(272, "Huyện A Lưới"),
                        new District(273, "Huyện Phong Điền"),
                        new District(274, "Huyện Quảng Điền"),
                        new District(275, "Huyện Nam Đông"),
                        new District(276, "Huyện Phú Lộc"),
                        new District(277, "Huyện Phú Vang"))),
                new Province(23, "Bắc Ninh", Arrays.asList(
                        new District(278, "Thành phố Bắc Ninh"),
                        new District(279, "Thị xã Từ Sơn"),
                        new District(280, "Huyện Gia Bình"),
                        new District(281, "Huyện Lương Tài"),
                        new District(282, "Huyện Quế Võ"),
                        new District(283, "Huyện Tiên Du"),
                        new District(284, "Huyện Yên Phong"),
                        new District(285, "Huyện Thuận Thành"),
                        new District(286, "Huyện Đông Anh"))),

                new Province(24, "Thanh Hóa", Arrays.asList(
                        new District(287, "Thành phố Thanh Hóa"),
                        new District(288, "Thị xã Bỉm Sơn"),
                        new District(289, "Huyện Bá Thước"),
                        new District(290, "Huyện Cẩm Thủy"),
                        new District(291, "Huyện Đông Sơn"),
                        new District(292, "Huyện Hà Trung"),
                        new District(293, "Huyện Hậu Lộc"),
                        new District(294, "Huyện Hoằng Hóa"),
                        new District(295, "Huyện Lang Chánh"),
                        new District(296, "Huyện Mường Lát"),
                        new District(297, "Huyện Nga Sơn"),
                        new District(298, "Huyện Ngọc Lặc"),
                        new District(299, "Huyện Như Xuân"),
                        new District(300, "Huyện Như Thanh"),
                        new District(301, "Huyện Nông Cống"),
                        new District(302, "Huyện Quảng Xương"),
                        new District(303, "Huyện Thạch Thành"),
                        new District(304, "Huyện Thiệu Hóa"),
                        new District(305, "Huyện Triệu Sơn"),
                        new District(306, "Huyện Tĩnh Gia"),
                        new District(307, "Huyện Vĩnh Lộc"),
                        new District(308, "Huyện Yên Định"))),
                new Province(25, "Long An", Arrays.asList(
                        new District(309, "Thành phố Tân An"),
                        new District(310, "Thị xã Kiến Tường"),
                        new District(311, "Huyện Bến Lức"),
                        new District(312, "Huyện Cần Đước"),
                        new District(313, "Huyện Cần Giuộc"),
                        new District(314, "Huyện Châu Thành"),
                        new District(315, "Huyện Đức Hòa"),
                        new District(316, "Huyện Đức Huệ"),
                        new District(317, "Huyện Mộc Hóa"),
                        new District(318, "Huyện Thạnh Hóa"),
                        new District(319, "Huyện Tân Trụ"),
                        new District(320, "Huyện Tân Hưng"),
                        new District(321, "Huyện Vĩnh Hưng"))),

                new Province(26, "Hòa Bình", Arrays.asList(
                        new District(322, "Thành phố Hòa Bình"),
                        new District(323, "Huyện Cao Phong"),
                        new District(324, "Huyện Đà Bắc"),
                        new District(325, "Huyện Kỳ Sơn"),
                        new District(326, "Huyện Lương Sơn"),
                        new District(327, "Huyện Mai Châu"),
                        new District(328, "Huyện Tân Lạc"),
                        new District(329, "Huyện Yên Thủy"),
                        new District(330, "Huyện Lạc Sơn"),
                        new District(331, "Huyện Lạc Thủy"),
                        new District(332, "Huyện Kim Bôi"))),

                new Province(27, "Ninh Thuận", Arrays.asList(
                        new District(333, "Thành phố Phan Rang - Tháp Chàm"),
                        new District(334, "Huyện Bác Ái"),
                        new District(335, "Huyện Ninh Hải"),
                        new District(336, "Huyện Ninh Phước"),
                        new District(337, "Huyện Thuận Bắc"),
                        new District(338, "Huyện Thuận Nam"),
                        new District(339, "Huyện Ninh Sơn"),
                        new District(340, "Huyện Bầu Bàng"))),
                new Province(28, "Bình Phước", Arrays.asList(
                        new District(341, "Thành phố Đồng Xoài"),
                        new District(342, "Thị xã Phước Long"),
                        new District(343, "Huyện Bù Đăng"),
                        new District(344, "Huyện Bù Đốp"),
                        new District(345, "Huyện Chơn Thành"),
                        new District(346, "Huyện Hớn Quản"),
                        new District(347, "Huyện Lộc Ninh"),
                        new District(348, "Huyện Phú Riềng"),
                        new District(349, "Huyện Đồng Phú"),
                        new District(350, "Huyện Bù Gia Mập"))),

                new Province(29, "Tiền Giang", Arrays.asList(
                        new District(351, "Thành phố Mỹ Tho"),
                        new District(352, "Thị xã Gò Công"),
                        new District(353, "Huyện Cái Bè"),
                        new District(354, "Huyện Cai Lậy"),
                        new District(355, "Huyện Châu Thành"),
                        new District(356, "Huyện Chợ Gạo"),
                        new District(357, "Huyện Tân Phước"),
                        new District(358, "Huyện Tân Hội"),
                        new District(359, "Huyện Gò Công Tây"),
                        new District(360, "Huyện Gò Công Đông"),
                        new District(361, "Huyện Thành phố Gò Công"),
                        new District(362, "Huyện Tân Hòa"))),

                new Province(30, "Đắk Nông", Arrays.asList(
                        new District(363, "Thành phố Gia Nghĩa"),
                        new District(364, "Huyện Cư Jút"),
                        new District(365, "Huyện Đắk Glong"),
                        new District(366, "Huyện Đắk Mil"),
                        new District(367, "Huyện Đắk R'lấp"),
                        new District(368, "Huyện Krông Nô"),
                        new District(369, "Huyện Tuy Đức"))),
                new Province(31, "Ninh Bình", Arrays.asList(
                        new District(370, "Thành phố Ninh Bình"),
                        new District(371, "Thị xã Tam Điệp"),
                        new District(372, "Huyện Gia Viễn"),
                        new District(373, "Huyện Hoa Lư"),
                        new District(374, "Huyện Kim Sơn"),
                        new District(375, "Huyện Nho Quan"),
                        new District(376, "Huyện Phát Diệm"),
                        new District(377, "Huyện Yên Khánh"),
                        new District(378, "Huyện Yên Mô"))),

                new Province(32, "Thái Bình", Arrays.asList(
                        new District(379, "Thành phố Thái Bình"),
                        new District(380, "Thị xã Quỳnh Phụ"),
                        new District(381, "Huyện Đông Hưng"),
                        new District(382, "Huyện Hưng Hà"),
                        new District(383, "Huyện Kiến Xương"),
                        new District(384, "Huyện Quỳnh Phụ"),
                        new District(385, "Huyện Thái Thụy"),
                        new District(386, "Huyện Tiền Hải"),
                        new District(387, "Huyện Vũ Thư"))),

                new Province(33, "Quảng Ngãi", Arrays.asList(
                        new District(388, "Thành phố Quảng Ngãi"),
                        new District(389, "Huyện Ba Tơ"),
                        new District(390, "Huyện Bình Sơn"),
                        new District(391, "Huyện Đức Phổ"),
                        new District(393, "Huyện Lý Sơn"),
                        new District(394, "Huyện Minh Long"),
                        new District(395, "Huyện Nghĩa Hành"),
                        new District(396, "Huyện Sơn Tịnh"),
                        new District(397, "Huyện Trà Bồng"),
                        new District(398, "Huyện Tư Nghĩa"))),
                new Province(34, "Hưng Yên", Arrays.asList(
                        new District(399, "Thành phố Hưng Yên"),
                        new District(400, "Huyện Ân Thi"),
                        new District(401, "Huyện Bình Giang"),
                        new District(402, "Huyện Khoái Châu"),
                        new District(403, "Huyện Kim Động"),
                        new District(404, "Huyện Mỹ Hào"),
                        new District(405, "Huyện Phù Cừ"),
                        new District(406, "Huyện Tiên Lữ"),
                        new District(407, "Huyện Văn Giang"),
                        new District(408, "Huyện Văn Lâm"),
                        new District(409, "Huyện Yên Mỹ"))),

                new Province(35, "Bắc Kạn", Arrays.asList(
                        new District(410, "Thành phố Bắc Kạn"),
                        new District(411, "Huyện Ba Bể"),
                        new District(412, "Huyện Bạch Thông"),
                        new District(413, "Huyện Chợ Đồn"),
                        new District(414, "Huyện Chợ Mới"),
                        new District(415, "Huyện Na Rì"),
                        new District(416, "Huyện Pác Nặm"),
                        new District(417, "Huyện Ngân Sơn"))),

                new Province(36, "Bắc Giang", Arrays.asList(
                        new District(418, "Thành phố Bắc Giang"),
                        new District(419, "Huyện Lạng Giang"),
                        new District(420, "Huyện Lục Nam"),
                        new District(421, "Huyện Lục Ngạn"),
                        new District(422, "Huyện Sơn Động"),
                        new District(423, "Huyện Tân Yên"),
                        new District(424, "Huyện Việt Yên"),
                        new District(425, "Huyện Yên Dũng"),
                        new District(426, "Huyện Hiệp Hòa"))),
                new Province(37, "Kon Tum", Arrays.asList(
                        new District(427, "Thành phố Kon Tum"),
                        new District(428, "Huyện Đăk Glei"),
                        new District(429, "Huyện Đăk Hà"),
                        new District(430, "Huyện Đăk Tô"),
                        new District(431, "Huyện Kon Plông"),
                        new District(432, "Huyện Kon Rẫy"),
                        new District(433, "Huyện Ngọc Hồi"),
                        new District(434, "Huyện Sa Thầy"),
                        new District(435, "Huyện Tu Mơ Rông"))),

                new Province(38, "Bến Tre", Arrays.asList(
                        new District(436, "Thành phố Bến Tre"),
                        new District(437, "Huyện Ba Tri"),
                        new District(438, "Huyện Bình Đại"),
                        new District(439, "Huyện Châu Thành"),
                        new District(440, "Huyện Chợ Lách"),
                        new District(441, "Huyện Giồng Trôm"),
                        new District(442, "Huyện Mỏ Cày Bắc"),
                        new District(443, "Huyện Mỏ Cày Nam"),
                        new District(444, "Huyện Thạnh Phú"),
                        new District(445, "Huyện Thành Phú"))),

                new Province(39, "Phú Thọ", Arrays.asList(
                        new District(446, "Thành phố Việt Trì"),
                        new District(447, "Thị xã Phú Thọ"),
                        new District(448, "Huyện Cẩm Khê"),
                        new District(449, "Huyện Đoan Hùng"),
                        new District(450, "Huyện Hạ Hòa"),
                        new District(451, "Huyện Lâm Thao"),
                        new District(452, "Huyện Phù Ninh"),
                        new District(453, "Huyện Tam Nông"),
                        new District(454, "Huyện Tân Sơn"),
                        new District(455, "Huyện Thanh Ba"),
                        new District(456, "Huyện Thanh Sơn"),
                        new District(457, "Huyện Yên Lập"))),
                new Province(40, "Hải Dương", Arrays.asList(
                        new District(458, "Thành phố Hải Dương"),
                        new District(459, "Thị xã Chí Linh"),
                        new District(460, "Huyện Bình Giang"),
                        new District(461, "Huyện Cẩm Giàng"),
                        new District(462, "Huyện Gia Lộc"),
                        new District(463, "Huyện Kim Thành"),
                        new District(464, "Huyện Kinh Môn"),
                        new District(465, "Huyện Ninh Giang"),
                        new District(466, "Huyện Thanh Miện"),
                        new District(467, "Huyện Tứ Kỳ"),
                        new District(468, "Huyện Nam Sách"),
                        new District(469, "Huyện An Dương"))),

                new Province(41, "Quảng Trị", Arrays.asList(
                        new District(470, "Thành phố Đông Hà"),
                        new District(471, "Thị xã Quảng Trị"),
                        new District(472, "Huyện Cam Lộ"),
                        new District(473, "Huyện Cồn Cỏ"),
                        new District(474, "Huyện Đakrông"),
                        new District(475, "Huyện Hải Lăng"),
                        new District(476, "Huyện Hướng Hóa"),
                        new District(477, "Huyện Triệu Phong"),
                        new District(478, "Huyện Vĩnh Linh"))),

                new Province(42, "Nam Định", Arrays.asList(
                        new District(479, "Thành phố Nam Định"),
                        new District(480, "Thị xã Mỹ Lộc"),
                        new District(481, "Huyện Giao Thủy"),
                        new District(482, "Huyện Hải Hậu"),
                        new District(483, "Huyện Nam Trực"),
                        new District(484, "Huyện Nghĩa Hưng"),
                        new District(485, "Huyện Trực Ninh"),
                        new District(486, "Huyện Vụ Bản"),
                        new District(487, "Huyện Xuân Trường"),
                        new District(488, "Huyện Ý Yên"))),
                new Province(43, "Trà Vinh", Arrays.asList(
                        new District(489, "Thành phố Trà Vinh"),
                        new District(490, "Huyện Cầu Kè"),
                        new District(491, "Huyện Cầu Ngang"),
                        new District(492, "Huyện Châu Thành"),
                        new District(493, "Huyện Duyên Hải"),
                        new District(494, "Huyện Long Đức"),
                        new District(495, "Huyện Tiểu Cần"),
                        new District(496, "Huyện Trà Cú"),
                        new District(497, "Huyện Vũng Liêm"))),

                new Province(44, "Tây Ninh", Arrays.asList(
                        new District(498, "Thành phố Tây Ninh"),
                        new District(499, "Huyện Bến Cầu"),
                        new District(500, "Huyện Dương Minh Châu"),
                        new District(501, "Huyện Gò Dầu"),
                        new District(502, "Huyện Hoà Thành"),
                        new District(503, "Huyện Châu Thành"),
                        new District(504, "Huyện Tân Biên"),
                        new District(505, "Huyện Tân Châu"))),

                new Province(45, "Bạc Liêu", Arrays.asList(
                        new District(506, "Thành phố Bạc Liêu"),
                        new District(507, "Huyện Đông Hải"),
                        new District(508, "Huyện Hòa Bình"),
                        new District(509, "Huyện Hồng Dân"),
                        new District(510, "Huyện Phước Long"),
                        new District(511, "Huyện Vĩnh Lợi"),
                        new District(512, "Huyện Giá Rai"),
                        new District(513, "Huyện Thành phố Bạc Liêu"))),

                // Thêm các tỉnh còn lại tương tự...
                new Province(57, "Cà Mau", Arrays.asList(
                        new District(500, "Thành phố Cà Mau"),
                        new District(501, "Cái Nước"),
                        new District(502, "Đầm Dơi"),
                        new District(503, "Năm Căn"),
                        new District(504, "Ngọc Hiển"),
                        new District(505, "Phú Tân"),
                        new District(506, "Thới Bình"),
                        new District(507, "Trần Văn Thời"),
                        new District(508, "U Minh"))));
    }
}
